# Generated by Django 5.2 on 2025-05-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.genre'),
        ),
    ]
