# Generated by Django 5.2 on 2025-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_alter_book_unique_together_book_file_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(db_index=True, default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=55),
        ),
    ]
