# Generated by Django 5.2 on 2025-05-19 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_surname_alter_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='age_restriction',
            field=models.CharField(default=1, help_text='Китеп сунушталат', max_length=4, validators=[django.core.validators.RegexValidator(message='Мисалы: "18+", "0+", "-6", "16" ж.б.', regex='^-?\\d{1,2}\\+$|^-?\\d{1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=True, help_text='Чыгарылган жылы', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(2025, message='Год не может быть больше 2025.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(help_text='Баасы', null=True, validators=[django.core.validators.MaxValueValidator(9999, message='Баасы 9999 ойдо боло албайт')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Китептин аталышы', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(to='books.language'),
        ),
    ]
