# Generated by Django 5.2 on 2025-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_af',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ar',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ar_dz',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ast',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_az',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_be',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_bg',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_bn',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_br',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_bs',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ca',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ckb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_cs',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_cy',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_da',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_de',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_dsb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_el',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_en',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_en_au',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_en_gb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_eo',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es_ar',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es_co',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es_mx',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es_ni',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_es_ve',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_et',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_eu',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_fa',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_fi',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_fr',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_fy',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ga',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_gd',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_gl',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_he',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_hi',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_hr',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_hsb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_hu',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_hy',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ia',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ig',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ind',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_io',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_is',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_it',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ja',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ka',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_kab',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_kk',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_km',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_kn',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ko',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ky',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_lb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_lt',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_lv',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_mk',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ml',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_mn',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_mr',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ms',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_my',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_nb',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ne',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_nl',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_nn',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_os',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_pa',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_pl',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_pt',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_pt_br',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ro',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ru',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sk',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sl',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sq',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sr',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sr_latn',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sv',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_sw',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ta',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_te',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_tg',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_th',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_tk',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_tr',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_tt',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_udm',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ug',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_uk',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_ur',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_uz',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_vi',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_zh_hans',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content_zh_hant',
            field=models.CharField(help_text='Кыскача мазмуну', max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_af',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ar',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ar_dz',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ast',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_az',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_be',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bg',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bn',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_br',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_bs',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ca',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ckb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_cs',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_cy',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_da',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_de',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_dsb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_el',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en_au',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en_gb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_eo',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es_ar',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es_co',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es_mx',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es_ni',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es_ve',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_et',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_eu',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fa',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fi',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fy',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ga',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_gd',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_gl',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_he',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_hi',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_hr',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_hsb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_hu',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_hy',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ia',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ig',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ind',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_io',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_is',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_it',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ja',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ka',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kab',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kk',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_km',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kn',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ko',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ky',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_lb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_lt',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_lv',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_mk',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ml',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_mn',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_mr',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ms',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_my',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_nb',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ne',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_nl',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_nn',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_os',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_pa',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_pl',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_pt',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_pt_br',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ro',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sk',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sl',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sq',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sr',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sr_latn',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sv',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sw',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ta',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_te',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tg',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_th',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tk',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tr',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tt',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_udm',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ug',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uk',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ur',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_vi',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_zh_hans',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_zh_hant',
            field=models.CharField(help_text='Китептин аталышы', max_length=150, null=True),
        ),
    ]
