# Generated by Django 5.2 on 2025-06-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_content_af_book_content_ar_book_content_ar_dz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=7000),
        ),
    ]
